import type {NextConfig} from 'next'
import {createClient} from 'next-sanity'
import drupalRedirects from './src/data/drupal-redirects.json'

type Redirect = {source: string; destination: string; permanent: boolean}

// Old Drupal paths (generated by scripts/import-drupal.ts) + editor-managed redirects from Sanity.
// Sanity redirects are read at build time; trigger a Vercel deploy hook when they change.
async function redirects(): Promise<Redirect[]> {
  const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
  let cms: Redirect[] = []
  if (projectId) {
    const client = createClient({
      projectId,
      dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
      apiVersion: '2026-10-01',
      useCdn: false,
      ...(process.env.SANITY_API_HOST ? {apiHost: process.env.SANITY_API_HOST, useProjectHostname: false} : {}),
    })
    cms = await client.fetch<Redirect[]>(`*[_type == "redirect" && defined(source) && defined(destination)]{source, destination, "permanent": coalesce(permanent, true)}`)
  }
  // Next matches the encoded request path, so non-ASCII sources (e.g. /skola/pasākumi) must be encoded.
  return [...drupalRedirects, ...cms].map((r) => ({...r, source: encodeURI(r.source).replace(/[()]/g, (c) => '\\' + c)}))
}

const nextConfig: NextConfig = {
  images: {remotePatterns: [{protocol: 'https', hostname: 'cdn.sanity.io'}]},
  redirects,
}

export default nextConfig
